<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DictionaryService.Contracts\DictionaryService.Contracts.csproj"/>
    <ProjectReference Include="..\DictionaryService.Domain\DictionaryService.Domain.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions"/>
    <PackageReference Include="Scrutor" />
  </ItemGroup>

</Project>
